### PR TITLE
Added `sourceOptions` param to use with `got`.

### PR DESCRIPTION
**Pull request by hefler**
This fixes if there's need for extra http.request options to be sent, such as authentication and so on.

### CODE REVIEW

**Comment by Haroenv** [comment]
thanks for your contribution! Could you also add that to the readme? Option and naming makes sense to me :)

**Review by Haroenv — APPROVED** [review]

**Comment by Haroenv** [comment]
This is released in 0.3.0 by the way :)

**Comment by hefler** [comment]
Great, thanks for making this lib  👍

**Comment by Haroenv** [comment]
With pleasure, would love to see what you're using it for, or more changes if you need them

**Pull request merged**
